# dapr/config/resiliency.yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: resiliencyconfig
scopes:
  - weatherclient


spec:
  policies:
    retries:
      retryForever:
        policy: constant
        maxInterval: 5s
        maxRetries: -1 

    circuitBreakers:
      simpleCB:
        maxRequests: 1
        timeout: 5s 
        trip: consecutiveFailures >= 5

  targets:
    apps:
      weatherservice:
        retry: retryForever
        circuitBreaker: simpleCB